In [1]:
import numpy as np

In [2]:
a = np.array([1,2,45,5,6])

In [3]:
a

array([ 1,  2, 45,  5,  6])

In [4]:
a.ndim

1

In [5]:
a1 = np.array([[1,23,4],[5,6,4],[5,4,7]])

In [6]:
a1

array([[ 1, 23,  4],
       [ 5,  6,  4],
       [ 5,  4,  7]])

In [7]:
a1.ndim

2

In [8]:
arr = np.arange(1,10)

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr1 = np.arange(1.5,10) # it can also generate float array data

In [11]:
arr1

array([1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [12]:
a1

array([[ 1, 23,  4],
       [ 5,  6,  4],
       [ 5,  4,  7]])

In [13]:
a1.shape

(3, 3)

In [14]:
a1.size

9

In [15]:
len(a1)

3

In [16]:
len(a)

5

**Generating array from function**

In [17]:
arr = np.fromfunction(lambda i,j : i,(5,5))

In [18]:
arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [19]:
arr = np.fromfunction(lambda i,j : i + j,(5,5))

In [20]:
arr

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.],
       [3., 4., 5., 6., 7.],
       [4., 5., 6., 7., 8.]])

In [21]:
iterable = (i*i for i in range(5))

In [22]:
arr = np.fromiter(iterable,int)

In [23]:
arr

array([ 0,  1,  4,  9, 16])

In [24]:
iterable1 = ((i*i,i*i*i) for i in range(5)) 

In [25]:
arr = np.fromiter(iterable1,(int ,2))

In [26]:
arr

array([[ 0,  0],
       [ 1,  1],
       [ 4,  8],
       [ 9, 27],
       [16, 64]])

In [27]:
np.fromstring('2 4 2 4 2 5 4',sep = ' ') # default data type  is float

array([2., 4., 2., 4., 2., 5., 4.])

In [28]:
np.fromstring('2-4-2-4-2-5-4',sep = '-',dtype=int) # also we can change data type

array([2, 4, 2, 4, 2, 5, 4])

In [29]:
a = np.linspace(1,10) # it gives 50 element (default) between (1 to 10)

In [30]:
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [31]:
a1 = np.linspace(1,10,5) # aslo we can specify the no. of element like 5

In [32]:
a1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
len(a1)

5

In [34]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
z = np.zeros((2,3))

In [37]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.zeros((2,3,4)) # two 3 by 4 matrix

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [39]:
np.zeros((2,3,4)).ndim

3

In [40]:
np.zeros((2,3,4,5)) 

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [41]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [42]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.empty((3,4)) 

array([[4.67486981e-310, 0.00000000e+000, 1.01855798e-312,
        9.54898106e-313],
       [1.18831764e-312, 1.03977794e-312, 1.23075756e-312,
        1.16709769e-312],
       [1.03977794e-312, 9.76118064e-313, 1.08221785e-312,
        1.90979621e-312]])

In [44]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
a = np.logspace(2,3,12)

In [46]:
a

array([ 100.        ,  123.28467394,  151.9911083 ,  187.38174229,
        231.01297001,  284.80358684,  351.11917342,  432.87612811,
        533.66992312,  657.93322466,  811.13083079, 1000.        ])

In [47]:
a.reshape(4,3)

array([[ 100.        ,  123.28467394,  151.9911083 ],
       [ 187.38174229,  231.01297001,  284.80358684],
       [ 351.11917342,  432.87612811,  533.66992312],
       [ 657.93322466,  811.13083079, 1000.        ]])

In [48]:
a.flatten() # convert into 1 dimensional array

array([ 100.        ,  123.28467394,  151.9911083 ,  187.38174229,
        231.01297001,  284.80358684,  351.11917342,  432.87612811,
        533.66992312,  657.93322466,  811.13083079, 1000.        ])

In [49]:
np.full((3,3),7.5) # create a array of specific number in given dimension

array([[7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5]])

In [50]:
np.random.random((2,5))

array([[0.77988294, 0.34059954, 0.76202553, 0.6681555 , 0.30582526],
       [0.4531085 , 0.82803883, 0.79511529, 0.18967066, 0.73543781]])

In [51]:
np.random.rand(2,5)

array([[0.51151461, 0.5798683 , 0.39058744, 0.15171645, 0.16778771],
       [0.62851365, 0.99517261, 0.70550204, 0.13380087, 0.04675308]])

In [52]:
np.random.randn(2,4)

array([[-0.23037833, -0.64820277, -2.12575399, -1.18460632],
       [-0.45778485, -0.98661339,  1.46173284, -0.76912525]])

In [53]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.00519995, -0.46123949,  0.71493111],
       [-0.16882925,  1.89586374, -0.95919189],
       [ 0.46348624,  0.61987526,  0.65745092]])

In [54]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 7, 5],
       [6, 9, 1],
       [5, 7, 6]])

**Indexing and Slicing**

In [55]:
# 1 dimensional indexing 
a = np.array([5,0,4,5,3,9])

In [56]:
a

array([5, 0, 4, 5, 3, 9])

In [57]:
a[3] # +ve indexing

5

In [58]:
a[-1] # -ve indexing

9

In [59]:
# 1 dimensional slicing
a

array([5, 0, 4, 5, 3, 9])

In [60]:
a[1:]

array([0, 4, 5, 3, 9])

In [61]:
a[:3]

array([5, 0, 4])

In [62]:
a[2:4]

array([4, 5])

In [63]:
a[1:5:3]

array([0, 3])

In [64]:
a[:-1] # -ve sllicing

array([5, 0, 4, 5, 3])

In [65]:
a

array([5, 0, 4, 5, 3, 9])

In [66]:
a[-1:]

array([9])

In [67]:
a[-4:]

array([4, 5, 3, 9])

In [68]:
# multi dimensional indexing
a1 = np.array([[5,3,9],[2,5,3],[8,3,6]])

In [69]:
a1 

array([[5, 3, 9],
       [2, 5, 3],
       [8, 3, 6]])

In [70]:
a1.ndim

2

In [71]:
a1[1] 

array([2, 5, 3])

In [72]:
a1[1][2]

3

In [73]:
a1[2,2]

6

In [74]:
# multi dimensional slicing
a1

array([[5, 3, 9],
       [2, 5, 3],
       [8, 3, 6]])

In [75]:
a1[1:]

array([[2, 5, 3],
       [8, 3, 6]])

In [76]:
a1[:2]

array([[5, 3, 9],
       [2, 5, 3]])

In [77]:
a1[0:1]

array([[5, 3, 9]])

In [78]:
a1

array([[5, 3, 9],
       [2, 5, 3],
       [8, 3, 6]])

In [79]:
a1[0:2:2]

array([[5, 3, 9]])

In [80]:
a1[0:1,]

array([[5, 3, 9]])

In [81]:
a1[0:1,0:2]

array([[5, 3]])

In [82]:
arr = np.random.randint(0, 10, (6, 6))

In [83]:
arr

array([[8, 9, 9, 3, 1, 2],
       [2, 5, 1, 6, 9, 0],
       [0, 6, 3, 2, 1, 5],
       [5, 1, 9, 7, 1, 5],
       [6, 3, 9, 7, 8, 3],
       [8, 4, 3, 4, 9, 0]])

In [84]:
arr[2:]

array([[0, 6, 3, 2, 1, 5],
       [5, 1, 9, 7, 1, 5],
       [6, 3, 9, 7, 8, 3],
       [8, 4, 3, 4, 9, 0]])

In [85]:
arr[2:5]

array([[0, 6, 3, 2, 1, 5],
       [5, 1, 9, 7, 1, 5],
       [6, 3, 9, 7, 8, 3]])

In [86]:
arr[2:5,1:]

array([[6, 3, 2, 1, 5],
       [1, 9, 7, 1, 5],
       [3, 9, 7, 8, 3]])

In [87]:
arr[2:5,1:4]

array([[6, 3, 2],
       [1, 9, 7],
       [3, 9, 7]])

In [88]:
arr[2:5,1:4:2]

array([[6, 2],
       [1, 7],
       [3, 7]])

In [89]:
arr[2:5:2,1:4:2]

array([[6, 2],
       [3, 7]])