## Sort ,search and count ##

In [1]:
import numpy as np

In [2]:
arr = np.array([5,7,5,6,45,78,1,12,28])

In [3]:
arr

array([ 5,  7,  5,  6, 45, 78,  1, 12, 28])

In [5]:
np.sort(arr)

array([ 1,  5,  5,  6,  7, 12, 28, 45, 78])

In [8]:
np.searchsorted(arr,27) # find the index to put the value in ascending order

4

In [9]:
a = np.array([2,4,5,0,0,0,0,0,0,4,0])

In [10]:
a

array([2, 4, 5, 0, 0, 0, 0, 0, 0, 4, 0])

In [12]:
np.count_nonzero(a) # it gives the no. of non zero values

4

In [15]:
arr

array([ 5,  7,  5,  6, 45, 78,  1, 12, 28])

In [17]:
np.where(arr==6) # it gives the index according to tthe condition

(array([3]),)

In [18]:
np.where(arr<6)

(array([0, 2, 6]),)

In [22]:
np.extract(arr>6,arr) # it gives the values according to the condition

array([ 7, 45, 78, 12, 28])