## Array manipulation ##

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,(5,6))

In [3]:
arr

array([[ 6, 18,  1, 15,  1,  9],
       [15, 16, 15, 19, 17, 15],
       [11, 14, 13,  7,  6,  6],
       [ 1, 10,  2, 18,  1,  9],
       [19,  5, 11, 14,  6, 14]])

In [4]:
arr.shape

(5, 6)

In [5]:
arr.reshape(3,10)

array([[ 6, 18,  1, 15,  1,  9, 15, 16, 15, 19],
       [17, 15, 11, 14, 13,  7,  6,  6,  1, 10],
       [ 2, 18,  1,  9, 19,  5, 11, 14,  6, 14]])

In [6]:
arr.flatten()

array([ 6, 18,  1, 15,  1,  9, 15, 16, 15, 19, 17, 15, 11, 14, 13,  7,  6,
        6,  1, 10,  2, 18,  1,  9, 19,  5, 11, 14,  6, 14])

In [7]:
arr1 = np.array([2,3,4,7,5])

In [8]:
arr1

array([2, 3, 4, 7, 5])

In [9]:
np.expand_dims(arr1,axis = 0) # increase the dimension

array([[2, 3, 4, 7, 5]])

In [10]:
np.expand_dims(arr1,axis = 1)

array([[2],
       [3],
       [4],
       [7],
       [5]])

In [11]:
arr1 = np.expand_dims(arr1,axis = (0,2)) 

In [12]:
arr1

array([[[2],
        [3],
        [4],
        [7],
        [5]]])

In [13]:
arr1.ndim

3

In [14]:
a = np.array([[2],[4],[8]])

In [15]:
a

array([[2],
       [4],
       [8]])

In [16]:
a.squeeze(axis=1)

array([2, 4, 8])

In [17]:
np.repeat(a,2)

array([2, 2, 4, 4, 8, 8])

In [18]:
a

array([[2],
       [4],
       [8]])

In [19]:
np.repeat(a,2,axis=1)

array([[2, 2],
       [4, 4],
       [8, 8]])

In [22]:
a = a.flatten()

In [23]:
a

array([2, 4, 8])

In [ ]:
a.roll()